### ISSUE TITLE
Proposal: Use pom.xml to describe the packaged plug-in

### ISSUE THREAD

**Issue by seanly** [kubesphere/ks-jenkins#75]
Currently, there are a problems with describing dependencies on plug-ins that need to be packaged in the plugins field of the formula file:

* After upgrading Jenkins version, all relevant plug-ins need to be re-confirmed one by one, otherwise the following errors will occur
![image](https://user-images.githubusercontent.com/232069/148557109-d1d69bec-0122-4b6d-bc92-f90f02a4d720.png)

# Proposal

Write the information about the plug-in to be packaged in the pom.xml file and reference it in the formula.yaml file as follows:

```yaml
# formula.yaml
bundle:
  groupId: io.github.ks-jenkins
  artifactId: ks-jenkins
  description: Jenkins formula for Kubesphere
  vendor: Kubesphere Community
buildSettings:
  docker:
    base: jenkins/jenkins:2.319.1
    tag: {{.tag}}
    output: {{.output}}
    platform: {{.platform}}
    buildx: true
    build: true
  pom: pom.xml
  pomIgnoreRoot: true
  pomIncludeWar: true
war:
  groupId: org.jenkins-ci.main
  artifactId: jenkins-war
  source:
    version: 2.319.1
systemProperties:
  hudson.security.csrf.DefaultCrumbIssuer.EXCLUDE_SESSION_ID: "true"
  jenkins.install.runSetupWizard: "false"
groovyHooks:
  - type: "init"
    id: "bundle-plugins"
    source:
      dir: remove-bundle-plugins.groovy

```
With the help of the plugin version relationships already sorted out by the community, only the `bom` needs to be updated when upgrading the Jenkins version

```xml
<!-- pom.xml -->
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.jenkins.tools.bom</groupId>
        <artifactId>bom-2.319.x</artifactId>
        <version>1090.v0a_33df40457a_</version>
        <scope>import</scope>
        <type>pom</type>
      </dependency>
    </dependencies>
  </dependencyManagement>
```

Add plug-in dependencies like this

```xml
  <dependencies>
    <!-- jenkins plugins -->
    <dependency>
      <groupId>org.jenkins-ci.plugins</groupId>
      <artifactId>token-macro</artifactId>
    </dependency>
    <dependency>
      <groupId>org.jenkins-ci.plugins</groupId>
      <artifactId>cloudbees-folder</artifactId>
    </dependency>
    <dependency>
      <groupId>org.jenkins-ci.plugins</groupId>
      <artifactId>credentials-binding</artifactId>
    </dependency>
    <dependency>
      <groupId>org.jenkins-ci.plugins.workflow</groupId>
      <artifactId>workflow-step-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.jenkins-ci.plugins</groupId>
      <artifactId>structs</artifactId>
    </dependency>
    <dependency>
      <groupId>org.jenkins-ci.plugins.workflow</groupId>
      <artifactId>workflow-cps</artifactId>
    </dependency>
    <dependency>
      <groupId>io.jenkins</groupId>
      <artifactId>configuration-as-code</artifactId>
      <version>1.55</version>
    </dependency>
    <dependency>
      <groupId>io.jenkins.blueocean</groupId>
      <artifactId>blueocean</artifactId>
      <version>1.25.2</version>
    </dependency>
  </dependencies>
```
